version: "3.5"
networks:
    external:
        driver: bridge
        name: twitter_chatbot

    database:
        driver: bridge
        name: twitter_analytics_db_network

services:
    db:
        container_name: twitter_chatbot_db
        image: postgres:13.3
        volumes:
          - ${HOST_POSTGRES_DIR}:/var/lib/postgresql/data
        environment:
          POSTGRES_PASSWORD: "${DB_PASSWORD}"
          POSTGRES_USER: "${DB_USER}"
          POSTGRES_DB: "${DB_NAME}"
        networks:
          - database
        logging:
          driver: "json-file"
          options:
            max-file: '100'
            max-size: 1m
        restart: unless-stopped

    analytics_server:
        build: .
        container_name: azmina-chatbot-analytics
        restart: unless-stopped
        depends_on:
            - db
        environment:
            PORT: 2049

            DB_HOST: db
            DB_PORT: 5432
            DB_USER: ${DB_USER}
            DB_PASSWORD: ${DB_PASSWORD}
            DB_NAME: ${DB_NAME}
        logging:
          driver: "json-file"
          options:
            max-file: '100'
            max-size: 1m
        expose:
            - 2049
        networks:
            - database
            - external
